// <auto-generated />
using System;
using EV_BatteryChangeStation_Repository.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EV_BatteryChangeStation_Repository.Migrations
{
    [DbContext(typeof(EvbatterySwapContext))]
    partial class EvbatterySwapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int?>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__349DA586C236EBB6");

                    b.HasIndex("RoleId");

                    b.HasIndex("StationId");

                    b.HasIndex(new[] { "Email" }, "UQ__Account__A9D105343631B7EE")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Battery", b =>
                {
                    b.Property<int>("BatteryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BatteryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatteryId"));

                    b.Property<DateTime?>("BatterySwapDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("InsuranceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("PercentUse")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("StateOfHealth")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TypeBattery")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BatteryId")
                        .HasName("PK__Battery__5710803E6A6769CC");

                    b.HasIndex("StationId");

                    b.ToTable("Battery", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    b.HasKey("BookingId")
                        .HasName("PK__Booking__73951ACDE8C52343");

                    b.HasIndex("AccountId");

                    b.HasIndex("StationId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Car", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("BatteryType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Producer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleId")
                        .HasName("PK__Car__476B54B2FBCD2BC6");

                    b.ToTable("Car", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDF6F3665690");

                    b.HasIndex("AccountId");

                    b.HasIndex("BookingId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionID");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A585E4E527C");

                    b.HasIndex(new[] { "TransactionId" }, "UQ__Payment__55433A4A74209A6B")
                        .IsUnique()
                        .HasFilter("[TransactionID] IS NOT NULL");

                    b.HasIndex(new[] { "SubscriptionId" }, "UQ__Payment__9A2B24BC99BDB0F9")
                        .IsUnique()
                        .HasFilter("[SubscriptionID] IS NOT NULL");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A71AC50DB");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin",
                            Status = false
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Staff",
                            Status = false
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Customer",
                            Status = false
                        });
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("AccountName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BatteryQuality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("StationId")
                        .HasName("PK__Station__E0D8A6DD21EBD158");

                    b.ToTable("Station", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DurationPackage")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExtraFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("SubscriptionId")
                        .HasName("PK__Subscrip__9A2B24BDAB8E8A64");

                    b.HasIndex("AccountId");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SupportRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IssueType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ResponseText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("RequestId")
                        .HasName("PK__SupportR__33A8519A9D6769AC");

                    b.HasIndex("AccountId");

                    b.HasIndex("StaffId");

                    b.ToTable("SupportRequest", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NewBatteryId")
                        .HasColumnType("int")
                        .HasColumnName("NewBatteryID");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OldBatteryId")
                        .HasColumnType("int")
                        .HasColumnName("OldBatteryID");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    b.HasKey("TransactionId")
                        .HasName("PK__Swapping__55433A4BF6A8C536");

                    b.HasIndex("NewBatteryId");

                    b.HasIndex("StaffId");

                    b.HasIndex("VehicleId");

                    b.ToTable("SwappingTransaction", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Account", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Account__RoleID__3E52440B");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("Accounts")
                        .HasForeignKey("StationId")
                        .HasConstraintName("FK__Account__Station__3F466844");

                    b.Navigation("Role");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Battery", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("Batteries")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("FK__Battery__Station__4E88ABD4");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Booking", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("Bookings")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Booking__Account__5441852A");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("Bookings")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("FK__Booking__Station__52593CB8");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Car", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK__Booking__Vehicle__534D60F1");

                    b.Navigation("Account");

                    b.Navigation("Station");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Feedback", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__Accoun__5DCAEF64");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Booking", "Booking")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__Bookin__5EBF139D");

                    b.Navigation("Account");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Payment", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Subscription", "Subscription")
                        .WithOne("Payment")
                        .HasForeignKey("EV_BatteryChangeStation_Repository.Entities.Payment", "SubscriptionId")
                        .HasConstraintName("FK__Payment__Subscri__48CFD27E");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", "Transaction")
                        .WithOne("Payment")
                        .HasForeignKey("EV_BatteryChangeStation_Repository.Entities.Payment", "TransactionId")
                        .HasConstraintName("FK__Payment__Transac__6754599E");

                    b.Navigation("Subscription");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Subscription", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Subscript__Accou__440B1D61");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SupportRequest", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("SupportRequestAccounts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_SupportRequest_User");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Staff")
                        .WithMany("SupportRequestStaffs")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_SupportRequest_Staff");

                    b.Navigation("Account");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Battery", "NewBattery")
                        .WithMany("SwappingTransactions")
                        .HasForeignKey("NewBatteryId")
                        .IsRequired()
                        .HasConstraintName("FK__SwappingT__NewBa__6383C8BA");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Staff")
                        .WithMany("SwappingTransactions")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__SwappingT__Staff__619B8048");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Car", "Vehicle")
                        .WithMany("SwappingTransactions")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK__SwappingT__Vehic__628FA481");

                    b.Navigation("NewBattery");

                    b.Navigation("Staff");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Account", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");

                    b.Navigation("Subscriptions");

                    b.Navigation("SupportRequestAccounts");

                    b.Navigation("SupportRequestStaffs");

                    b.Navigation("SwappingTransactions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Battery", b =>
                {
                    b.Navigation("SwappingTransactions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Booking", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Car", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("SwappingTransactions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Station", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Batteries");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Subscription", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", b =>
                {
                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
