// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class EVBatterySwapContext : DbContext
{
    public EVBatterySwapContext(DbContextOptions<EVBatterySwapContext> options)
        : base(options)
    {
    }
    public EVBatterySwapContext()
    {
    }
    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Battery> Batteries { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Car> Cars { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    public virtual DbSet<Subscription> Subscriptions { get; set; }

    public virtual DbSet<SupportRequest> SupportRequests { get; set; }

    public virtual DbSet<SwappingTransaction> SwappingTransactions { get; set; }

    private string GetConnectionString()
    {
        IConfiguration config = new ConfigurationBuilder()
             .SetBasePath(AppContext.BaseDirectory)
                    .AddJsonFile("appsettings.json", true, true)
                    .Build();
        var strConn = config["ConnectionStrings:DefaultConnection"];
        return strConn;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(GetConnectionString());
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Account__349DA58610EDBFEB");

            entity.ToTable("Account");

            entity.HasIndex(e => e.Email, "UQ__Account__A9D1053404247062").IsUnique();

            entity.Property(e => e.AccountId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("AccountID");
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.FullName).HasMaxLength(150);
            entity.Property(e => e.Gender).HasMaxLength(10);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.StationId).HasColumnName("StationID");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Role).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Account__RoleID__412EB0B6");

            entity.HasOne(d => d.Station).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__Account__Station__4222D4EF");
        });

        modelBuilder.Entity<Battery>(entity =>
        {
            entity.HasKey(e => e.BatteryId).HasName("PK__Battery__5710803E93CBC715");

            entity.ToTable("Battery", tb =>
                {
                    tb.HasTrigger("trg_AfterDelete_Battery");
                    tb.HasTrigger("trg_AfterInsert_Battery");
                });

            entity.Property(e => e.BatteryId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("BatteryID");
            entity.Property(e => e.BatterySwapDate).HasColumnType("datetime");
            entity.Property(e => e.Capacity).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.LastUsed).HasColumnType("datetime");
            entity.Property(e => e.PercentUse).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.StateOfHealth).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.StationId).HasColumnName("StationID");
            entity.Property(e => e.TypeBattery).HasMaxLength(100);

            entity.HasOne(d => d.Station).WithMany(p => p.Batteries)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Battery__Station__5535A963");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Booking__73951ACD33E9B5D6");

            entity.ToTable("Booking");

            entity.Property(e => e.BookingId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("BookingID");
            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DateTime).HasColumnType("datetime");
            entity.Property(e => e.Notes).HasMaxLength(100);
            entity.Property(e => e.StationId).HasColumnName("StationID");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

            entity.HasOne(d => d.Account).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Booking__Account__5BE2A6F2");

            entity.HasOne(d => d.Station).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Booking__Station__59FA5E80");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Booking__Vehicle__5AEE82B9");
        });

        modelBuilder.Entity<Car>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__Car__476B54B2D4FE9422");

            entity.ToTable("Car");

            entity.Property(e => e.VehicleId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("VehicleID");
            entity.Property(e => e.BatteryType).HasMaxLength(100);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Model).HasMaxLength(100);
            entity.Property(e => e.Producer).HasMaxLength(100);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Available");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__Feedback__6A4BEDF6A819A88C");

            entity.ToTable("Feedback");

            entity.Property(e => e.FeedbackId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("FeedbackID");
            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.BookingId).HasColumnName("BookingID");
            entity.Property(e => e.Comment).HasMaxLength(255);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Account).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Feedback__Accoun__6754599E");

            entity.HasOne(d => d.Booking).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Feedback__Bookin__68487DD7");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__9B556A58774C3B19");

            entity.ToTable("Payment");

            entity.HasIndex(e => e.TransactionId, "UQ__Payment__55433A4AE2F8AF80").IsUnique();

            entity.Property(e => e.PaymentId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("PaymentID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Method).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");
            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");

            entity.HasOne(d => d.Subscription).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SubscriptionId)
                .HasConstraintName("FK__Payment__Subscri__4CA06362");

            entity.HasOne(d => d.Transaction).WithOne(p => p.Payment)
                .HasForeignKey<Payment>(d => d.TransactionId)
                .HasConstraintName("FK__Payment__Transac__72C60C4A");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE3A0BD21A37");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("RoleID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.StationId).HasName("PK__Station__E0D8A6DDEDE92D96");

            entity.ToTable("Station");

            entity.Property(e => e.StationId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("StationID");
            entity.Property(e => e.AccountName).HasMaxLength(100);
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
        });

        modelBuilder.Entity<Subscription>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK__Subscrip__9A2B24BD06733C93");

            entity.ToTable("Subscription");

            entity.Property(e => e.SubscriptionId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("SubscriptionID");
            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.ExtraFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Account).WithMany(p => p.Subscriptions)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Subscript__Accou__47DBAE45");
        });

        modelBuilder.Entity<SupportRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__SupportR__33A8519A3AEF46DC");

            entity.ToTable("SupportRequest");

            entity.Property(e => e.RequestId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("RequestID");
            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IssueType).HasMaxLength(100);
            entity.Property(e => e.ResponseDate).HasColumnType("datetime");
            entity.Property(e => e.ResponseText).HasMaxLength(255);
            entity.Property(e => e.StaffId).HasColumnName("StaffID");

            entity.HasOne(d => d.Account).WithMany(p => p.SupportRequestAccounts)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupportRequest_User");

            entity.HasOne(d => d.Staff).WithMany(p => p.SupportRequestStaffs)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("FK_SupportRequest_Staff");
        });

        modelBuilder.Entity<SwappingTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__Swapping__55433A4BE58BD394");

            entity.ToTable("SwappingTransaction");

            entity.Property(e => e.TransactionId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("TransactionID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NewBatteryId).HasColumnName("NewBatteryID");
            entity.Property(e => e.Notes).HasMaxLength(255);
            entity.Property(e => e.OldBatteryId).HasColumnName("OldBatteryID");
            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Active");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

            entity.HasOne(d => d.NewBattery).WithMany(p => p.SwappingTransactions)
                .HasForeignKey(d => d.NewBatteryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SwappingT__NewBa__6EF57B66");

            entity.HasOne(d => d.Staff).WithMany(p => p.SwappingTransactions)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SwappingT__Staff__6C190EBB");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.SwappingTransactions)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SwappingT__Vehic__6D0D32F4");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}