// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class Account
{
    public Guid AccountId { get; set; }

    public string AccountName { get; set; }

    public string FullName { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public bool Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public Guid RoleId { get; set; }

    public Guid? StationId { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Role Role { get; set; }

    public virtual Station Station { get; set; }

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();

    public virtual ICollection<SupportRequest> SupportRequestAccounts { get; set; } = new List<SupportRequest>();

    public virtual ICollection<SupportRequest> SupportRequestStaffs { get; set; } = new List<SupportRequest>();

    public virtual ICollection<SwappingTransaction> SwappingTransactions { get; set; } = new List<SwappingTransaction>();
}