// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class Battery
{
    public Guid BatteryId { get; set; }

    public decimal? Capacity { get; set; }

    public DateTime? LastUsed { get; set; }

    public bool? Status { get; set; }

    public decimal? StateOfHealth { get; set; }

    public decimal? PercentUse { get; set; }

    public string TypeBattery { get; set; }

    public DateTime? BatterySwapDate { get; set; }

    public DateOnly? InsuranceDate { get; set; }

    public Guid StationId { get; set; }

    public virtual Station Station { get; set; }

    public virtual ICollection<SwappingTransaction> SwappingTransactions { get; set; } = new List<SwappingTransaction>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}