// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class Booking
{
    public Guid BookingId { get; set; }

    public DateTime DateTime { get; set; }

    public string Notes { get; set; }

    public string IsApproved { get; set; }

    public DateTime? CreatedDate { get; set; }

    public Guid StationId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid AccountId { get; set; }

    public Guid? BatteryId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Station Station { get; set; }

    public virtual Car Vehicle { get; set; }
}