// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class Feedback
{
    public Guid FeedbackId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreateDate { get; set; }

    public Guid AccountId { get; set; }

    public Guid BookingId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Booking Booking { get; set; }
}