// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public decimal? Price { get; set; }

    public string Method { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public Guid? SubscriptionId { get; set; }

    public Guid? TransactionId { get; set; }

    public virtual Subscription Subscription { get; set; }

    public virtual SwappingTransaction Transaction { get; set; }
}