// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public decimal? Price { get; set; }

    public string Method { get; set; }

    public string Status { get; set; }

    public long? PaymentGateId { get; set; }

    public DateTime? CreateDate { get; set; }

    public Guid? SubscriptionId { get; set; }

    public Guid? TransactionId { get; set; }

    /// <summary>
    /// AccountId của user mua subscription (bắt buộc nếu có SubscriptionId)
    /// </summary>
    public Guid? AccountId { get; set; }

    public virtual Subscription Subscription { get; set; }

    public virtual SwappingTransaction Transaction { get; set; }

    public virtual Account Account { get; set; }
}