// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class Station
{
    public Guid StationId { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public bool? Status { get; set; }

    public string StationName { get; set; }

    public int? BatteryQuantity { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual ICollection<Battery> Batteries { get; set; } = new List<Battery>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}