// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class Subscription
{
    public Guid SubscriptionId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public decimal? ExtraFee { get; set; }

    public string Description { get; set; }

    public int? DurationPackage { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    // Ngày bắt đầu hiệu lực gói cho user (khi gắn với Account)
    public DateTime? StartDate { get; set; }

    // Ngày hết hạn gói cho user
    public DateTime? EndDate { get; set; }

    // Số lượt swap còn lại (nếu gói có giới hạn lượt)
    public int? RemainingSwaps { get; set; }

    public Guid? AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}