// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class SupportRequest
{
    public Guid RequestId { get; set; }

    public string IssueType { get; set; }

    public string Description { get; set; }

    public DateTime? CreateDate { get; set; }

    public bool? Status { get; set; }

    public Guid AccountId { get; set; }

    public Guid? StaffId { get; set; }

    public string ResponseText { get; set; }

    public DateTime? ResponseDate { get; set; }

    public virtual Account Account { get; set; }

    public virtual Account Staff { get; set; }
}