// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV_BatteryChangeStation_Repository.Entities;

public partial class SwappingTransaction
{
    public Guid TransactionId { get; set; }

    public string Notes { get; set; }

    public Guid StaffId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid NewBatteryId { get; set; }

    public string Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual Battery NewBattery { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual Account Staff { get; set; }

    public virtual Car Vehicle { get; set; }
}